server:
  port: 8081

spring:
  application:
    name: display

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 #default 1초
      circuitBreaker:
        requestVolumeThreshold: 1 #default 20
        erorrThresholdPercentage: 50 #defalut 50

product:
  ribbon:
    listOfServers: localhost:8082, localhost:7777
    MaxAutoRetries: 0
    MaxAutoRetriesNextServer: 1